package io.legado.app.constant

object EventBus {
    const val MEDIA_BUTTON = "mediaButton"
    const val RECREATE = "RECREATE"
    const val UP_BOOKSHELF = "upBookToc"
    const val BOOKSHELF_REFRESH = "bookshelfRefresh"
    const val BOOKSHELF_STRUCTURE_CHANGED = "bookshelfStructureChanged"
    const val ALOUD_STATE = "aloud_state"
    const val READ_ALOUD_PLAYBACK_STATE = "readAloudPlaybackState"
    const val TTS_PROGRESS = "ttsStart"
    const val READ_ALOUD_PROGRESS = "readAloudProgress"
    const val NOVEL_AUDIO_PREPARATION = "novelAudioPreparation"
    const val AUDIO_DS = "audioDs"
    const val READ_ALOUD_DS = "readAloudDs"
    const val READ_ALOUD_PANEL_ACTIVE = "readAloudPanelActive"
    const val BATTERY_CHANGED = "batteryChanged"
    const val TIME_CHANGED = "timeChanged"
    const val UP_CONFIG = "upConfig"
    const val VIDEO_SUB_TITLE = "VideoSubTitle"
    const val AUDIO_SUB_TITLE = "audioSubTitle"
    const val AUDIO_STATE = "audioState"
    const val AUDIO_PROGRESS = "audioProgress"
    const val AUDIO_BUFFER_PROGRESS = "audioBufferProgress"
    const val AUDIO_SIZE = "audioSize"
    const val AUDIO_SPEED = "audioSpeed"
    const val NOTIFY_MAIN = "notifyMain"
    const val WEB_SERVICE = "webService"
    const val UP_DOWNLOAD = "upDownload"
    const val UP_DOWNLOAD_STATE = "upDownloadState"
    const val SAVE_CONTENT = "saveContent"
    const val CHECK_SOURCE = "checkSource"
    const val CHECK_SOURCE_DONE = "checkSourceDone"
    const val CHECK_RSS_SOURCE = "checkRssSource"
    const val CHECK_RSS_SOURCE_DONE = "checkRssSourceDone"
    const val TIP_COLOR = "tipColor"
    const val SOURCE_CHANGED = "sourceChanged"
    const val SEARCH_RESULT = "searchResult"
    const val UPDATE_READ_ACTION_BAR = "updateReadActionBar"
    const val READ_MENU_BUTTON_CHANGED = "readMenuButtonChanged"
    const val CONTENT_SELECT_MENU_CONFIG_CHANGED = "contentSelectMenuConfigChanged"
    const val UP_SEEK_BAR = "upSeekBar"
    const val READ_ALOUD_PLAY = "readAloudPlay"
    const val READ_ALOUD_CONFIG_CHANGED = "readAloudConfigChanged"
    const val READ_ALOUD_CONFIG_SCOPE = "scope"
    const val READ_ALOUD_CONFIG_SCOPE_AUDIO = "audio"
    const val READ_ALOUD_CONFIG_SCOPE_SPEECH = "speech"
    const val READ_ALOUD_CONFIG_SCOPE_ENGINE = "engine"
    const val AI_READ_ALOUD_ROLE_STATE = "aiReadAloudRoleState"
    const val AI_CONFIG_CHANGED = "aiConfigChanged"
    const val EXPORT_BOOK = "exportBook"
    const val UP_MANGA_CONFIG = "upMangaConfig"
    const val PLAY_MODE_CHANGED = "playModeChanged"
    const val REFRESH_BOOK_INFO = "refreshBookInfo"
    const val REFRESH_BOOK_CONTENT = "refreshBookContent"
    const val REFRESH_BOOK_TOC = "refreshBookToc"
    const val LIBRARY_CONTAINER_CHANGED = "libraryContainerChanged"
    const val UP_VIDEO_INFO = "upVideoInfo"
    const val VIDEO_PLAY_ERROR = "videoPlayError"
    // video-booksource-align-rss AD-02：书源列表切换影片完成信号（显式激活链）
    const val VIDEO_BOOK_UNIT_SWITCHED = "videoBookUnitSwitched"
    // video-sniff-403-and-rss-classic-fix Phase 2 (3.6)：VIDEO_FALLBACK_WEBVIEW 事件常量已删除
    // （WebView 播放器移除，原 WebView 承接点统一改发 VIDEO_PLAY_ERROR"重试/系统浏览器"）
    const val ARTICLES_LOADED = "articlesLoaded"
    // 阅读页滚动模式顶部下拉快速书签 (R5)
    const val PULL_DOWN_BOOKMARK = "pullDownBookmark"
    // T6（theme-arch-gap）：MAIN_THEME_BACKGROUND_CHANGED 死事件常量已删（4 发 0 订阅）
    // P1E：外观套件切换信号（AppearanceKitManager 等 config 类使用）
    const val MAIN_APPEARANCE_KIT_CHANGED = "mainAppearanceKitChanged"
    // Archive 主界面：导航栏 / 顶栏重载信号
    const val NAVIGATION_BAR_CHANGED = "navigationBarChanged"
    const val TOP_BAR_CHANGED = "topBarChanged"
}
